name: CI

on:
  push:
    branches: ["main", "renovate/*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno check main.ts
      - run: deno lint
        if: always()
